amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    laser_model_type: "likelihood_field"
    max_particles: 2000
    min_particles: 500
    update_min_d: 0.25
    update_min_a: 0.2
map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "/home/ser/FYP/ros2_ws/src/fyp_bot/maps/L_shaped_corridor.yaml"
    
bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0 # Locked: 10 Hz
    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      max_vel_x: 0.22
      max_vel_theta: 2.84
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      vx_samples: 20
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0 # Locked: 1 Hz
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true # Fixed: True
      width: 4          # Fixed: 4.0m
      height: 4        # Fixed: 4.0m
      resolution: 0.05     # Fixed: 0.05
      robot_radius: 0.105  # Fixed: TB3 standard
      plugins: ["obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: True
          clearing: True
          obstacle_max_range: 2.5 # Fixed: 3.0m
          raytrace_max_range: 3.0 # Fixed: 3.5m
          
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.35    # Fixed: 0.35m
        cost_scaling_factor: 2.0  # Fixed: 2.0
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      robot_base_frame: base_footprint
      resolution: 0.05           # Fixed: 0.05
      robot_radius: 0.105        # Fixed: TB3 standard
      track_unknown_space: true  # Fixed: True
      plugins: ["static_layer", "inflation_layer"] # No obstacle layer as per criteria
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25    # Fixed: 0.35m
        cost_scaling_factor: 3.0  # Fixed: 2.0
      always_send_full_costmap: True