import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import rosbag2_py
from scipy.interpolate import interp1d
from rclpy.serialization import deserialize_message
from rosidl_runtime_py.utilities import get_message
import os

def get_bag_data(bag_path, topic_name):
    """extract (timestamp, x, y) from a ROS2 bag file"""
    reader = rosbag2_py.SequentialReader()
    
    # storage options
    storage_options = rosbag2_py.StorageOptions(uri=bag_path, storage_id='sqlite3')
    converter_options = rosbag2_py.ConverterOptions(input_serialization_format='cdr', output_serialization_format='cdr')
    
    try:
        reader.open(storage_options, converter_options)
    except Exception as e:
        print(f"Error opening bag at {bag_path}: {e}")
        return None

    topic_types = reader.get_all_topics_and_types()
    type_map = {topic.name: topic.type for topic in topic_types}

    if topic_name not in type_map:
        print(f"Topic {topic_name} not found in bag.")
        return None
    
    msg_type = get_message(type_map[topic_name])
    data = []

    while reader.has_next():
        (topic, raw_msg, timestamp) = reader.read_next()
        if topic == topic_name:
            msg = deserialize_message(raw_msg, msg_type)
            
            # --- MODIFIED: SLAM Toolbox Logic ---
            # SLAM Toolbox publishes localization on '/pose'
            if topic_name == '/pose':
                data.append([timestamp, msg.pose.pose.position.x, msg.pose.pose.position.y])
            
            # Logic for Ground Truth (Gazebo)
            elif topic_name == '/ground_truth':
                data.append([timestamp, msg.pose.pose.position.x, msg.pose.pose.position.y])
    
    return pd.DataFrame(data, columns=['time', 'x', 'y'])

def get_completion_time(parent_dir):
    """Read the nav_time.txt file generated by the recorder"""
    time_file = os.path.join(parent_dir, "nav_time.txt")
    nav_time = "N/A"
    if os.path.exists(time_file):
        with open(time_file, 'r') as f:
            for line in f:
                if "nav_time_s" in line:
                    try:
                        nav_time = float(line.split(":")[1].strip())
                        nav_time = f"{nav_time:.2f} s"
                    except:
                        pass
    else:
        print("Warning: nav_time.txt not found.")
    return nav_time

def plot_and_calculate(parent_dir):
    print(f"Analyzing SLAM Toolbox dataset in: {parent_dir}")
    
    # 1. Locate the actual bag file
    bag_path = os.path.join(parent_dir, "bag")
    if not os.path.exists(bag_path):
        bag_path = parent_dir
    
    gt_topic = "/ground_truth"
    slam_topic = "/pose"  # CHANGED: SLAM Toolbox uses /pose, AMCL uses /amcl_pose
    
    # 2. Get Data
    df_slam = get_bag_data(bag_path, slam_topic)
    df_gt = get_bag_data(bag_path, gt_topic)

    if df_slam is None or df_gt is None or df_slam.empty or df_gt.empty: 
        print("Error: Missing topics or empty data in bag. (Check if '/pose' exists)")
        return

    # 3. Synchronize timestamps (interpolation)
    df_gt = df_gt.sort_values('time')
    f_x = interp1d(df_gt['time'], df_gt['x'], fill_value="extrapolate")
    f_y = interp1d(df_gt['time'], df_gt['y'], fill_value="extrapolate")
    
    df_slam['gt_x'] = f_x(df_slam['time'])
    df_slam['gt_y'] = f_y(df_slam['time'])

    # 4. Calculate RMSE (Trajectory Accuracy)
    error = np.sqrt((df_slam['x'] - df_slam['gt_x'])**2 + (df_slam['y'] - df_slam['gt_y'])**2)
    rmse = np.sqrt(np.mean(error**2))

    # --- NEW CALCULATION: LOOP CLOSURE ERROR ---
    # Metric: Distance between Final Estimated Pose (SLAM) and Initial Ground Truth Pose
    
    start_gt_x = df_gt['x'].iloc[0]
    start_gt_y = df_gt['y'].iloc[0]
    
    end_est_x = df_slam['x'].iloc[-1]
    end_est_y = df_slam['y'].iloc[-1]
    
    loop_closure_error = np.sqrt((end_est_x - start_gt_x)**2 + (end_est_y - start_gt_y)**2)
    
    print(f"--- RESULTS ---")
    print(f"RMSE (Trajectory Error): {rmse:.4f} m")
    print(f"Loop Closure Error:      {loop_closure_error:.4f} m")
    print(f"(End SLAM Est vs Start GT)")

    # 5. Get Time of Completion
    completion_time = get_completion_time(parent_dir)

    # 6. Create Visual Graph
    plt.figure(figsize=(10, 8))
    plt.plot(df_gt['x'], df_gt['y'], 'k--', label='Ground Truth', alpha=0.5)
    plt.plot(df_slam['x'], df_slam['y'], 'g-', label='Estimated Path (SLAM Toolbox)', linewidth=2)

    # Visualization: Draw a specific line for Loop Closure Error
    # Connects the Final Estimated Point to the Start Ground Truth Point
    plt.plot([end_est_x, start_gt_x], [end_est_y, start_gt_y], 
             color='magenta', linewidth=2, linestyle=':', label='Loop Closure Error')
    
    # Visualization: Add error lines for the trajectory
    step = max(1, len(df_slam) // 50)
    for i in range(0, len(df_slam), step):
        plt.plot([df_slam['x'].iloc[i], df_slam['gt_x'].iloc[i]],
                 [df_slam['y'].iloc[i], df_slam['gt_y'].iloc[i]], 'r-', alpha=0.3)
    
    # Updated Title with Metrics
    title_text = (f'SLAM Toolbox vs Ground Truth (Loop Analysis)\n'
                  f'RMSE: {rmse:.4f} m | Loop Err: {loop_closure_error:.4f} m\n'
                  f'Time: {completion_time}')
    plt.title(title_text)
    
    plt.xlabel('X Position (m)')
    plt.ylabel('Y Position (m)')
    plt.legend()
    plt.grid(True)
    plt.axis('equal') # Ensure the loop looks like a square, not a rectangle

    # Save to the PARENT folder
    save_path = os.path.join(parent_dir, 'slam_toolbox_loop_analysis.png')
    plt.savefig(save_path)
    print(f"Graph saved to: {save_path}")
    plt.show()

if __name__ == "__main__":
    # Point to the PARENT folder
    # Example: "/home/ser/FYP/ros2_ws/src/fyp_bot/fyp_bot/SLAMToolbox_bag_20260113_014509"
    PARENT_DIR = "/home/ser/FYP/ros2_ws/src/fyp_bot/fyp_bot/SLAMToolbox_bag_20260113_031250" 
    
    if os.path.exists(PARENT_DIR):
        plot_and_calculate(PARENT_DIR)
    else:
        print(f"Path not found: {PARENT_DIR}")
