import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import rosbag2_py
from scipy.interpolate import interp1d
from rclpy.serialization import deserialize_message
from rosidl_runtime_py.utilities import get_message
import os

def get_bag_data(bag_path, target_topic):
    """extract (timestamp, x, y) from a ROS2 bag file"""
    reader = rosbag2_py.SequentialReader()
    
    # storage options
    storage_options = rosbag2_py.StorageOptions(uri=bag_path, storage_id='sqlite3')
    converter_options = rosbag2_py.ConverterOptions(input_serialization_format='cdr', output_serialization_format='cdr')
    
    try:
        reader.open(storage_options, converter_options)
    except Exception as e:
        print(f"Error opening bag at {bag_path}: {e}")
        return None

    topic_types = reader.get_all_topics_and_types()
    type_map = {topic.name: topic.type for topic in topic_types}

    # Debugging: Print topics found if the target is missing
    if target_topic not in type_map:
        print(f"Error: Topic '{target_topic}' not found in bag.")
        print(f"Available topics: {list(type_map.keys())}")
        return None
    
    msg_type = get_message(type_map[target_topic])
    data = []

    while reader.has_next():
        (topic, raw_msg, timestamp) = reader.read_next()
        
        # Check if the current message matches the topic we are looking for
        if topic == target_topic:
            msg = deserialize_message(raw_msg, msg_type)
            
            # Handle standard PoseWithCovarianceStamped messages (used by all SLAMs)
            if hasattr(msg, 'pose') and hasattr(msg.pose, 'pose'):
                data.append([timestamp, msg.pose.pose.position.x, msg.pose.pose.position.y])
            
            # Handle Ground Truth Odometry messages
            elif hasattr(msg, 'pose') and hasattr(msg.pose, 'position'):
                data.append([timestamp, msg.pose.pose.position.x, msg.pose.pose.position.y])

    return pd.DataFrame(data, columns=['time', 'x', 'y'])

def get_completion_time(parent_dir):
    """Read the nav_time.txt file generated by the recorder"""
    time_file = os.path.join(parent_dir, "nav_time.txt")
    nav_time = "N/A"
    if os.path.exists(time_file):
        with open(time_file, 'r') as f:
            for line in f:
                if "nav_time_s" in line:
                    try:
                        nav_time = float(line.split(":")[1].strip())
                        nav_time = f"{nav_time:.2f} s"
                    except:
                        pass
    return nav_time

def plot_and_calculate(parent_dir):
    print(f"Analyzing Cartographer dataset in: {parent_dir}")
    
    # Handle folder structure (manual vs auto)
    bag_path = os.path.join(parent_dir, "bag")
    if not os.path.exists(bag_path):
        bag_path = parent_dir
    
    gt_topic = "/ground_truth"
    slam_topic = "/cartographer_pose" 
    
    # 2. Get Data
    df_slam = get_bag_data(bag_path, slam_topic)
    df_gt = get_bag_data(bag_path, gt_topic)

    if df_slam is None or df_slam.empty: 
        print(f"Error: SLAM data is empty for {slam_topic}")
        return
    if df_gt is None or df_gt.empty:
        print(f"Error: Ground Truth data is empty for {gt_topic}")
        return

    # 3. Synchronize timestamps (interpolation)
    df_gt = df_gt.sort_values('time')
    f_x = interp1d(df_gt['time'], df_gt['x'], fill_value="extrapolate")
    f_y = interp1d(df_gt['time'], df_gt['y'], fill_value="extrapolate")
    
    df_slam['gt_x'] = f_x(df_slam['time'])
    df_slam['gt_y'] = f_y(df_slam['time'])

    # 4. Calculate RMSE
    error = np.sqrt((df_slam['x'] - df_slam['gt_x'])**2 + (df_slam['y'] - df_slam['gt_y'])**2)
    rmse = np.sqrt(np.mean(error**2))

    # 5. Get Time of Completion
    completion_time = get_completion_time(parent_dir)

    # 6. Create Visual Graph
    plt.figure(figsize=(10, 8))
    plt.plot(df_gt['x'], df_gt['y'], 'k--', label='Ground Truth', alpha=0.5)
    plt.plot(df_slam['x'], df_slam['y'], 'c-', label='Estimated Path (Cartographer)', linewidth=2) 

    # Add error lines (visualization)
    step = max(1, len(df_slam) // 50) 
    for i in range(0, len(df_slam), step):
        plt.plot([df_slam['x'].iloc[i], df_slam['gt_x'].iloc[i]],
                 [df_slam['y'].iloc[i], df_slam['gt_y'].iloc[i]], 'r-', alpha=0.3)
    
    plt.title(f'Cartographer vs Ground Truth\nRMSE: {rmse:.4f} m | Time: {completion_time}')
    plt.xlabel('X Position (m)')
    plt.ylabel('Y Position (m)')
    plt.legend()
    plt.grid(True)
    plt.axis('equal')

    save_path = os.path.join(parent_dir, 'cartographer_graph.png')
    plt.savefig(save_path)
    print(f"Graph saved to: {save_path}")
    plt.show()

if __name__ == "__main__":
    # Update this path to your Cartographer bag folder
    # PARENT_DIR = "/home/ser/FYP/ros2_ws/src/fyp_bot/fyp_bot/Cartographer_bag_20260113_191033"
    
    # Or rely on your manual bag if the auto one is empty:
    PARENT_DIR = "/home/ser/FYP/ros2_ws/src/fyp_bot/fyp_bot/Cartographer_bag_20260115_170814"
    
    if os.path.exists(PARENT_DIR):
        plot_and_calculate(PARENT_DIR)
    else:
        print(f"Path not found: {PARENT_DIR}")
